### ISSUE TITLE
Alignment to PGx regions only 

### ISSUE THREAD

**Issue by kokyriakidis** [0xTCG/aldy#17]
Hello,

Do you think it would be a good idea to subset the human reference genome file so as it includes only PGx regions + some regions for normalization? Is this something feasible? Will Aldy work with an approach like that?

I want to speed up the process using WGS data.

**Comment by inumanag** [comment]
Hi @kokyriakidis, 
Yes, I don't see a reason why it should not. Just make sure to include pseudogenes (check Aldy's yml files for the exact regions; add an extra mb on sides and you should be good to go).

**Comment by muzic194** [comment]
Hello @kokyriakidis,
Could you managed to do alignment from WGS data only to Pgx regions? I would like to use the same way. 
How long flanking extra regions have you used? 
Where have you found pseudogenes regions? Are pseudogenes regions described in yml files somewhere? 
Have you extracted proper regions from yml files and do you have them in some bed or another format which could you share?

**Comment by inumanag** [comment]
@muzic194 

I would use 1 Mbp flanks on both side. You can get the list of all PGx regions Aldy supports via `aldy profile`, e.g.:

```
aldy profile aldy/tests/resources/NA10860.bam > /dev/null
🐿  Aldy v3.1 (Python 3.7.5 on macOS 10.16)
   (c) 2016-2021 Aldy Authors. All rights reserved.
   Free for non-commercial/academic use only.
Scanning 1:60355979-98392615...
Scanning 6:18125541-18161374...
Scanning 7:1016834-99467173...
Scanning 10:96516437-135355620...
Scanning 11:14896554-14919751...
Scanning 12:21278127-21395730...
Scanning 13:48605702-48629878...
Scanning 15:75008882-75051948...
Scanning 19:15985833-41716444...
Scanning 22:42518175-42549249...
Scanning X:153756605-153781787...
```

Take these regions and add an extra MB on the side and you're good to go (these regions cover all pseudogenes that Aldy supports).
