### ISSUE TITLE
Aldy test Assertion Error for the new year :)

### ISSUE THREAD

**Issue by rrdavis77** [0xTCG/aldy#18]
I have a working version of Aldy 1.2 but wanted to try 3.0.  When I tested version 3.0 with `aldy test` I received 16 failed test because of an assertion error in the test script test_full.py.
Changing the date in test_full.py from `2016-2020` to `2016-2021` resolved those errors.

**Comment by inumanag** [comment]
Thanks for spotting this one! Fixed in v3.1.
