### ISSUE TITLE
ERROR: gene= CYP1A2

### ISSUE THREAD

**Issue by deb0612** [0xTCG/aldy#20]
Dear sir,
I had trouble excute Aldy 3.1 in CYP1A2 gene.
Actually, this error won't appear if the bam file was aligned to Grch37 human genpome but to Grch38.
![image](https://user-images.githubusercontent.com/29038270/111723958-5ad4b880-889f-11eb-939b-d2b8bebe549f.png)

**Comment by inumanag** [comment]
Thank you for reporting this!

This issue has been resolved in the v3.2 that has just been released.
