### ISSUE TITLE
G6PD genotype

### ISSUE THREAD

**Issue by jucosie** [0xTCG/aldy#23]
Hi, 

I would like to report an error in the genotyping of G6PD. If I am not mistaken, G6PD is located on the X chromosome, and therefore we can have homozygous or heterozygous females, but males will only be hemizygous. I think Aldy interprets this gene as diploid in all cases, because when running it on patient exomes it does not distinguish between those with XX or XY.

Thanks

**Comment by inumanag** [comment]
Hi @jucosie 

Apologies for the delay. I have added an option `--male` with which you can indicate that the sample is male sample (i.e., it has one copy of X and Y gene). The support for automatic detection from the WGS/stable coverage data might be coming soon as well.
