### ISSUE TITLE
Providing --phase parameter for Aldy

### ISSUE THREAD

**Issue by AlirezaTafazzoli** [0xTCG/aldy#24]
Hi, I am working with Aldy and need to provide --phase parameter for more accurate calling of novel star alleles.
I used HapCUT2, based on the related documentation and received both "haplotype_output_file" and "haplotype_output_file.phased.VCF". 
But when I use any of them as phase parameter, I will face these errors respectively:

ERROR: gene= CYP2D6, file= A2_3_11_s53_S48.recal.bam
ValueError("invalid literal for int() with base 10: 'POS'")

and

ERROR: gene= cyp2d6, profile= illumina, file= A2_3_11_s53_S48.recal.bam
Invalid phasing line 1 in haplotype_output_file.phased.VCF (less than 7 columns)

Is anybody can tell me why it's happening and what should I do about that?

**Comment by inumanag** [comment]
Hi @AlirezaTafazzoli 

The problem is that Aldy expects HapTree-X/HapCUT phasing format. If you pass a VCF, you get an error (this is a bug, and I'll try to fix the message later on).

**Comment by AlirezaTafazzoli** [comment]
Thank you very much @inumanag 
I did it again and tried to remove a few lines which HapCUT did not put an integer for the result.
Then I used this modified version of HapCUT output and everything worked fine in Aldy.

**Comment by pauline-ng** [comment]
@AlirezaTafazzoli 
I'm getting this error too. I'm passing in the HapCUT phasing format. Can you tell me what you mean by "remove a few lines which HapCUT did not put an integer for the result." ?

**Comment by pauline-ng** [comment]
I figured it out:

 `cat  hapcut2_haplotype_file  | awk '{if ($2 != "-" && $3 != "-") { print}}' > hapcut2_haplotype_cleaned`
 
 and then pass in the hapcut2_haplotype_cleaned into Aldy

**Comment by AlirezaTafazzoli** [comment]
@pauline-ng 
Thanks for providing this.
