### ISSUE TITLE
Multiple Bam Files Into a Single Output File?

### ISSUE THREAD

**Issue by joseph-yclam** [0xTCG/aldy#28]
Is there a way to run multiple BAM files in Aldy and have the results from each BAM file contained in a single output file? When I try running each BAM file at a time to the same output file, it overwrites the data from the previous one.

**Comment by inumanag** [comment]
Hi @joseph-yclam 

You can do `aldy <bam> -o <bam_output>` and then collect all files into a single file. Another way to do this is to use stdout as the output: `aldy <bam> -o - >> collected_output`. You can also add `--simple` (recently added) to get a one-line summary of the call (e.g., `aldy <bam> --simple -o - >> collected_output`).
