### ISSUE TITLE
Update Aldy gene databases to latest PharmVar Version

### ISSUE THREAD

**Issue by InvictusX10A** [0xTCG/aldy#30]
Could you update Aldy’s gene databases that are based on Pharmvar.  The current pharmvar database is version 5.1.6.  The ones in the current Aldy v3.3 is from 4.1.7.  Also, there is a new gene added to PharmVar, SLCO1B1.  In Aldy v3.3, the SLCO1B1 allele definitions are based on PharmGKB.  Could you also update SLCO1B1 allele definitions to be based on PharmVar instead of PharmGKB?

-Best,

Reynold

**Comment by PWSmit** [comment]
Understandable that this is important but also a lot of work for the developers to keep it updated. Would it be an option if we collaborate on this? I am willing to help with a few genes for example, if there is some guidance how to do it? 

thanks, 
Pieter

**Comment by inumanag** [comment]
Hi @InvictusX10A @PWSmit 

The #31 branch now contains the latest PharmVar (v5.2.1) updates.

**Comment by PWSmit** [comment]
sorry, seems you forgot the bottom part of the gene list? what about TPMT, UGT1A1, vkor1c, ugt2b7?

**Comment by inumanag** [comment]
@PWSmit those are at their latest versions already (they are not on PharmVar; LMK if I made a mistake here). I will be cross-referencing them soon with the another database for completeness.

**Comment by PWSmit** [comment]
Awesome! Great work

Van: Ibrahim Numanagić ***@***.***>
Verzonden: maandag 15 augustus 2022 20:11
Aan: 0xTCG/aldy ***@***.***>
CC: PWSmit ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [0xTCG/aldy] Update Aldy gene databases to latest PharmVar Version (Issue #30)


Hi @InvictusX10A<https://github.com/InvictusX10A> @PWSmit<https://github.com/PWSmit>

The #31<https://github.com/0xTCG/aldy/pull/31> branch now contains the latest PharmVar (v5.2.1) updates.
