### ISSUE TITLE
Multiple BAM files?

### ISSUE THREAD

**Issue by JARM89** [0xTCG/aldy#32]
Is it possible to merge BAM files and make aldy to read them at the same time? Is it necessary to read BAM files one by one? Thank you in advance.

**Comment by inumanag** [comment]
Hi @JARM89 ,

I don't understand the question. Do you want to genotype multiple samples in multiple BAMs, or a single sample in multiple BAMs? In the later case, you can use `samtools merge` before running Aldy; otherwise, you will need to run Aldy for each sample separately.

**Comment by inumanag** [comment]
One way to run Aldy on many samples:

`parallel --bar 'aldy -g [gene] -p [profile] {} -o {}.aldy -l {}.log' ::: *.bam`

This will run Aldy and store outputs in `[bam].aldy` and logs in `[bam].log`. You can use `{/.}.aldy` to store the logs in the current dictionary (`{/.}` just uses the base name of the BAM file).
