### ISSUE TITLE
Copy number neutral region

### ISSUE THREAD

**Issue by sumudu-rangika** [0xTCG/aldy#35]
Hi,

I tried Aldy using 'vdr' gene region as -n instead of CYP2D8 default region. Below is the command I ran.

$aldy genotype -p illumina -g cyp2d6 -n 12:47811535-47945000 -o $out $bam

My Bam files are GRCh38 aligned. Aldy works well when I use default CYP2D8 as CN neutral region. But for VDR gene (also I tried egfr - both of these are used as CN neutral in Stargazer tool) I get an error 'coverage for CYP2D6 is too low for copy number calling'. But my Bam files have ~30X coverage. Any comments on why am I getting this error? 

Thanks 
Best
Sumudu

**Comment by inumanag** [comment]
Hi @sumudu-rangika 

Please try the latest Aldy (#31 branch) and see if this is still a problem—I've made quite a few changes that should ideally resolve this issue. Is this region (12:47811535-47945000) sequenced in the sample?
