### ISSUE TITLE
phase error

### ISSUE THREAD

**Issue by Keshavsrikar** [0xTCG/aldy#36]
Hi, 
When im trying to run the --phase , im getting the following error , 
![Error](https://user-images.githubusercontent.com/105855216/175023400-3a7d5431-5aa2-4e4c-822d-d5dd86157f51.png)
Please advise on how to rectify it.

**Comment by inumanag** [comment]
Hi @Keshavsrikar 

The old phasing support is retired (it was buggy anyways). Please use the new Aldy 4.0 (#31 — will be merged soon) for integrated phasing support that does not require HapTree-X.
