### ISSUE TITLE
Some gene cannot be accessed

### ISSUE THREAD

**Issue by deb0612** [0xTCG/aldy#38]
Dear sir,
I tried **aldy genotype -p illumina -g UGT1A1 my.bam**
and got the following information:
🐿  Aldy v3.1 (Python 3.8.10 on Linux 5.4.0-121-generic-x86_64-with-glibc2.29)
   (c) 2016-2022 Aldy Authors. All rights reserved.
   Free for non-commercial/academic use only.
Genotyping sample my.bam...
**ERROR: ugt1a1 cannot be accessed**
The same massage when doing gene IFNL3, NAT2, UGT1A1, VKORC1

**Comment by inumanag** [comment]
Hi @deb0612 

Can you please try #31 (aldy-4) branch and see if you experience the same problem? It should be fixed there.

**Comment by inumanag** [comment]
Resolved in the latest version [v4; master branch]
