### ISSUE TITLE
Aldy test error

### ISSUE THREAD

**Issue by deb0612** [0xTCG/aldy#39]
Dear sir,
I do aldy test, and show the following error:
![image](https://user-images.githubusercontent.com/29038270/185323535-43b4ca0c-5477-4221-82fc-d39f8cd433e1.png)
It seens that I got a missing file.
![image](https://user-images.githubusercontent.com/29038270/185324215-6ab68777-1898-4df2-8a88-42d1c661cdbc.png)

**Comment by inumanag** [comment]
Fixed in #40
