### ISSUE TITLE
aldy test failed

### ISSUE THREAD

**Issue by CryALotz** [0xTCG/aldy#42]
Hi,
i do `aldy test` and got a following failed :
<img width="633" alt="Screen Shot 2565-11-07 at 11 14 25" src="https://user-images.githubusercontent.com/39818286/200225378-0d4356b6-b360-4f4d-8477-51cba0ba403d.png">
<img width="602" alt="image" src="https://user-images.githubusercontent.com/39818286/200227529-c962a1a1-781d-4fef-aeb3-7e486e6fd143.png">

env:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/39818286/200225451-7bda4346-6b41-4ff5-ae1c-7d096b659c51.png">
after dig into it i thought it might be involve this part :
<img width="956" alt="image" src="https://user-images.githubusercontent.com/39818286/200225617-869b7ec5-db58-4e81-af28-674ab77876ed.png">

**Comment by anh151** [comment]
I am getting the same error using Python 3.9.15 on Linux.

**Comment by inumanag** [comment]
Hi @anh151 @CryALotz 

You can ignore this error for now (it's a packaging error, will be fixed soon). Aldy should work well if other tests passed.

**Comment by inumanag** [comment]
Fixed in v4.4.

**Comment by jlac** [comment]
Just a head up, I am still getting the same error in v4.4
