### ISSUE TITLE
CYP3A4 and rs2740574 handling

### ISSUE THREAD

**Issue by aroon-color** [0xTCG/aldy#46]
Hello,

We have been evaluating Aldy 4.4 alongside other PGx callers and noticed that `rs2740574` is handled a little strangely. We've seen two buckets of similar errors:
1. Despite being a homozygous call, Aldy appears to treat the variant as heterozygous/assign both copies to one diplotype 
2. Or, the correct suballele call is not being made when `rs2740574` is present

Aldy command in used both examples:
```
aldy genotype \
    --profile illumina \
    --gene cyp3a4 \
    --output test.default.cyp3a4.aldy \
    --genome hg19 \
    SAMPLE_1.bam \
    -v T \
    -l test.default.cyp3a4.aldylog
```

## `*1B/*1A`, should be `*1A/\*1A`
Full debug log: [*1B/*1 test.default.cyp3a4.aldylog.txt](https://github.com/0xTCG/aldy/files/10270840/test.default.cyp3a4.aldylog.txt)

Aldy correctly infers the copy number solution

```
[cn] result= CNSol[0.00; sol=(2x*1); cn=22222222222222222222222222222] (provided)
Potential CYP3A4 gene structures for SAMPLE_1:
   1: 2x*1 (confidence: 100%)
```

And then correctly detects a near ~2x copynumber for rs2740574

```
rs2740574    99382096.C>T    -390G>A    (cov= 344, cn= 1.9;
```

But in the final solution, instead of calling two `*1A`s one of each `*1A` and `*1B` are called:
```
    Minor: [*1.001] / [*1.002]
    Legacy notation: [*1B] / [*1A]
```
and both copies of `rs2740574` are assigned to allele 1 (`*1.002`) instead of being split evenly. 

## `*1.002/*(36.001 +rs2740574)` should be `*1.002, *36.002`

Full debug log: [sample_2.default.cyp3a4.aldylog.txt](https://github.com/0xTCG/aldy/files/10270928/sample_2.default.cyp3a4.aldylog.txt)

Aldy correctly infers the cn solution:
```
[cn] result= CNSol[0.00; sol=(2x*1); cn=22222222222222222222222222222] (provided)
Potential CYP3A4 gene structures for SAMPLE_2:
   1: 2x*1 (confidence: 100%)
```

And correctly detects the `rs2740574` cn
```
rs2740574    99382096.C>T    -390G>A    (cov= 401, cn= 2.0; 
```
But ultimately calls
```
    Minor: [*1.002] / [*36.001 +rs2740574]
    Legacy notation: [*1A] / [*36.001 +rs2740574]
```

`*36.002` **is** in fact `*36.001 + rs2740574`?

-----

I'm happy to provide subsetted and anonymized BAMs privately if it will help.

**Comment by inumanag** [comment]
Hi @aroon-color,

Thank you‚(belatedly) happy new year as well!

1. The first case happens because Aldy prefers to keep existing mutations, even if their support is low. You can "fix" this by adjusting `minor_miss` parameter (e.g., `-param minor_miss=0.5`; default is 1.5). Let me know if adjusting this does not work.

2. This is a funny one :) Seems to be happening because of one stray read that confuses the phasing module. For now, you can probably ignore this; I will try to patch this in the next release.

**Comment by aroon-color** [comment]
@inumanag Just following up here.  Setting `-param minor_miss=0.5` worked - thanks for that pointer! I totally missed the doc section on using `-params XXX=YY`.

Do you have a timeline for when 4.5 might be released?

**Comment by inumanag** [comment]
Hi @aroon-color 

I don't have any fixed timeline right now.
