### ISSUE TITLE
ERROR: gene= ifnl3, profile= wgs, file= 1_HB00001.cram The average coverage of the sample is too low (1.3).

### ISSUE THREAD

**Issue by SammyTTA** [0xTCG/aldy#49]
Hi there, 

I have tried genotyping with CRAM file using Aldy.
But I have a issue.

$ aldy genotype -p wgs -g ifnl3 1_HB00001.cram --reference GRCh38.p12.genome.fa -o test_1_HB00001-ifnl3.aldy
🐿  Aldy v4.2.1 (Python 3.9.13 on Linux 3.10.0-1062.4.1.el7.x86_64-x86_64-with-glibc2.17)
   (c) 2016-2023 Aldy Authors. All rights reserved.
   Free for non-commercial/academic use only.
Genotyping sample 1_HB00001.cram...
ERROR: gene= ifnl3, profile= wgs, file= 1_HB00001.cram
**The average coverage of the sample is too low (1.3).**

**Is there any way to ignore the average coverage of the VCF file I used as input and just get the output when I genotyping using Aldy?**
Please help me.....

Thak you

**Comment by inumanag** [comment]
Hi @SammyTTA 

The only way to disable the check for now is to clone Aldy yourself and remove the check here:
https://github.com/0xTCG/aldy/blob/d20f202a732d7a486ce3406d7e8b1a9c3e351bc2/aldy/sam.py#L124

I will consider adding an option for this in the next release.
