### ISSUE TITLE
IndexError: string index out of range for Nanopore data 

### ISSUE THREAD

**Issue by kiflu-23** [0xTCG/aldy#52]
I am trying to genotype cyp2d6 gene from Nanopore data (target sequencing) but kept giving me this error:

Traceback (most recent call last): ... /aldy/sam.py", line 389, in _realign_indels
    valn = VariantAlignment(  # type: ignore
IndexError: string index out of range
IndexError: string index out of range

I tried everything but couldn't fix it. 

Would you please help me?

Thank you

**Comment by inumanag** [comment]
This seems to be indelpost (external dependency) error. Can I get some more information (exact log, invocation, etc... : you can reach out to me via email if needed).

P.S. Aldy+Nanopore is still not officially supported. It does work, but detailed testing is pending.

**Comment by LynnLy** [comment]
Hi @kiflu-23 I encountered this with nanopore data too, but I think this fixed it:
After generating a custom profile for my panel, I needed to add this to the beginning of my profile file. 
```
options:
  sam_long_reads: true
```

**Comment by inumanag** [comment]
@LynnLy : that is correct---thank you ! I will upload the documentation.
