### ISSUE TITLE
Failed pytest after installation

### ISSUE THREAD

**Issue by pbrennan-mvz** [0xTCG/aldy#55]
Hello! I just installed aldy without any errors using 'pip install aldy', but when I do 'aldy test' a few of the tests failed. Is this expected?

![image](https://github.com/0xTCG/aldy/assets/103113037/e17725be-4dc9-45a0-8987-47c7db5b4491)

**Comment by inumanag** [comment]
It should be fine—tests are mostly used for CI right now.

**Comment by inumanag** [comment]
Should be fixed in 4.5—please reopen if it happens again.
