### ISSUE TITLE
Using Aldy with nanopore data - error for some genes

### ISSUE THREAD

**Issue by KoenDeserranno** [0xTCG/aldy#56]
Dear

Thanks for the great tool. We know that the combination of Aldy with Nanopore data is not fully supported yet, however, could you help me out with this error?

EDIT: I added the debug .tar file for CYP2A6. 
[DEBUG.tar.gz](https://github.com/0xTCG/aldy/files/11650604/DEBUG.tar.gz)

I created a specific profile for our nanopore data by using

`aldy profile /data/projects/pass_sorted.bam --genome hg38 > nanopore.profile
`

Next, I used the code to get the diplotypes for my data:

`aldy genotype -p nanopore.profile --genome hg38  pass_sorted.bam
`

For some genes (e.g. COMT), Aldy runs succesful. For others, it gives error ('IndexError: string index out of range') as stated below. Sometimes, a result is provided despite the error (e.g. CFTR), sometimes not (e.g. CYP2A6). Examples are given below. Any advice is much appreciated!

`🐿  Aldy v4.4 (Python 3.7.12 on Linux 3.10.0-1062.12.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core)
   (c) 2016-2023 Aldy Authors. All rights reserved.
   Free for non-commercial/academic use only.
Genotyping sample pass_sorted.bam...`

**Gene CFTR**
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
Potential CFTR gene structures for pass_sorted:
   1: 2x*1 (confidence: 100%)
Potential major CFTR star-alleles for pass_sorted:
   1: 2x*WT (confidence: 100%)
Best CFTR star-alleles for pass_sorted:
   1: *WT / *WT (confidence=100%)
      Minor alleles: *WT, *WT
CFTR results:
  - *WT / *WT
    Minor: [*WT] / [*WT]
    Legacy notation: [*WT] / [*WT]
    Estimated activity for *WT: unknown
    Estimated activity for *WT: unknown

**Gene COMT**
Potential COMT gene structures for pass_sorted:
   1: 2x*1 (confidence: 100%)
Potential major COMT star-alleles for pass_sorted:
   1: 1x*Met, 1x*ValA (confidence: 100%)
Best COMT star-alleles for pass_sorted:
   1: *Met / *ValA (confidence=100%)
      Minor alleles: *(Met +rs174699 +rs165599 +rs165728), *(ValA +rs2020917 +rs13306278 +rs737866 +rs737865 +rs737864 +rs5746849 +rs740603 +rs4646312 +rs2239393 +rs174699 +rs9332377 +rs165728)
COMT results:
  - *Met / *ValA
    Minor: [*Met +rs174699 +rs165599 +rs165728] / [*ValA +rs2020917 +rs13306278 +rs737866 +rs737865 +rs737864 +rs5746849 +rs740603 +rs4646312 +rs2239393 +rs174699 +rs9332377 +rs165728]
    Legacy notation: [*Met +rs174699 +rs165599 +rs165728] / [*ValA +rs2020917 +rs13306278 +rs737866 +rs737865 +rs737864 +rs5746849 +rs740603 +rs4646312 +rs2239393 +rs174699 +rs9332377 +rs165728]
    Estimated activity for *Met: unknown
    Estimated activity for *ValA: unknown

**Gene CYP2A6**
Ignoring utr3 in 5.001
Ignoring utr3 in 7.001
Ignoring utr3 in 8.001
Ignoring utr3 in 10.001
Ignoring utr3 in 19.001
Ignoring utr3 in 24.001
Ignoring utr3 in 24.002
Ignoring utr3 in 28.001
Ignoring utr3 in 28.002
Ignoring utr3 in 35.001
Ignoring utr3 in 35.002
Ignoring utr3 in 36.001
Ignoring utr3 in 37.001
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
IndexError: string index out of range
Exception ignored in: 'aldy.indelpost.utilities.count_lowqual_non_ref_bases'
IndexError: string index out of range
ERROR: gene= all, file= pass_sorted.bam
IndexError('string index out of range')
Traceback (most recent call last):
  File "/home/kdserran/miniconda3/envs/PGx/lib/python3.7/site-packages/aldy/__main__.py", line 122, in main
    _genotype(args.gene, output, args)
  File "/home/kdserran/miniconda3/envs/PGx/lib/python3.7/site-packages/aldy/__main__.py", line 443, in _genotype
    run(None)
  File "/home/kdserran/miniconda3/envs/PGx/lib/python3.7/site-packages/aldy/__main__.py", line 403, in run
    **{k: v for k, v in params.items() if v is not None},
  File "/home/kdserran/miniconda3/envs/PGx/lib/python3.7/site-packages/aldy/genotype.py", line 140, in genotype
    **params,
  File "/home/kdserran/miniconda3/envs/PGx/lib/python3.7/site-packages/aldy/genotype.py", line 186, in genotype
    sample = sam.Sample(gene, profile, sam_path, reference, debug)
  File "/home/kdserran/miniconda3/envs/PGx/lib/python3.7/site-packages/aldy/sam.py", line 111, in __init__
    norm, muts = self._load_sam(path, reference, debug)
  File "/home/kdserran/miniconda3/envs/PGx/lib/python3.7/site-packages/aldy/sam.py", line 162, in _load_sam
    self._realign_indels(tmp, sam, reference)
  File "/home/kdserran/miniconda3/envs/PGx/lib/python3.7/site-packages/aldy/sam.py", line 395, in _realign_indels
    exact_match_for_shiftable=exact_match_for_shiftable,
  File "aldy/indelpost/varaln.pyx", line 169, in aldy.indelpost.varaln.VariantAlignment.__cinit__
  File "aldy/indelpost/varaln.pyx", line 205, in aldy.indelpost.varaln.VariantAlignment.__parse_pileup
  File "aldy/indelpost/gappedaln.pyx", line 34, in aldy.indelpost.gappedaln.find_by_normalization
  File "aldy/indelpost/gappedaln.pyx", line 130, in aldy.indelpost.gappedaln.is_target_by_normalization
  File "aldy/indelpost/localn.pyx", line 123, in aldy.indelpost.localn.findall_mismatches
IndexError: string index out of range

**Comment by LynnLy** [comment]
Hi @KoenDeserranno, have you tried adding this line to your `nanopore.profile`?
```
options:
  sam_long_reads: true
```

Or run Aldy with the option `--param sam_long_reads=true`?

**Comment by inumanag** [comment]
Hi @KoenDeserranno 

Apologies for the late reply. This looks like a problem with the indelpost library that does not handle well long reads. 
As @LynnLy said, `--param sam_long_reads=True` will help as it will disable indelpost postprocessing.
