### ISSUE TITLE
FEATURE: Allow processing of files with multiple samples

### ISSUE THREAD

**Issue by yousef337** [0xTCG/aldy#57]
Allowing Aldy to process files that contain multiple samples will shorten the manual work of separating large files with large samples into a different file each

**Comment by yousef337** [comment]
#58

**Comment by inumanag** [comment]
Hi @yousef337 

I have added support for setting VCF sample via `--param vcf_sample_idx=N`, where N is a sample index (0-based). Now you should be able to parallelize Aldy easily via `parallel` command.
