### ISSUE TITLE
cn neutral region option does not work properly

### ISSUE THREAD

**Issue by seokho92** [0xTCG/aldy#59]
Hi, I am trying to use aldy with cram files. 
When I try to use other cn neutral region, aldy seems to go back to cyp2d8 region. 
`aldy genotype --genome hg38 -r GRCh38_full_analysis_set_plus_decoy_hla.fa -p wes -o example.wes_cram.out -l example.wes_cram.log example.cram -n chr7:55019016-55211628`

 First part of the log looks like this:
🐿  Aldy v4.4 (Python 3.6.5 on Linux 5.15.0-1031-aws-x86_64-with-debian-buster-sid)
   (c) 2016-2023 Aldy Authors. All rights reserved.
   Free for non-commercial/academic use only.
Genotyping sample example.cram...

Gene CFTR
Failed gene CFTR
Message: CN-neutral region 22:42151472-42152258 has no reads. Double check your input file for CYP2D8 (are you using hg19?), or pass an alternative CN-neutral region via -n parameter.

Any help on this will be appreciated..

**Comment by inumanag** [comment]
Fixed in v4.5
