### ISSUE TITLE
Aldy profile Creation

### ISSUE THREAD

**Issue by sahalpaladan** [0xTCG/aldy#60]
I want to run aldy for a targeted sequencing.so am planing  to create profile using bam file i have(same bam file is using for genotype).But i don't know about the copy number neutral region.Is there any way to find copy number neutral region from bam file?also i have one doubt will aldy create any wrong call when am run with this profile (created using aldy profile with default (cyp2d8)copy number neutral region?)

**Comment by inumanag** [comment]
Hi @sahalpaladan 

The best way to do it is to get your target BED and find a gene that is unlikely to have copy number changes. Which one—that really depends on your targets. You might need to try few of them until you find a stable enough region. In addition to CYP2D8, I also used IFGL3.
