### ISSUE TITLE
ALDY's detection of insertion and deletion variants

### ISSUE THREAD

**Issue by yscindyliu** [0xTCG/aldy#61]
Hello,

I am currently using ALDY for genotyping my samples, and I have come across an issue regarding the detection of insertion and deletion variants in the samples. It seems that ALDY is unable to identify variants with insertions or deletions, which leads to incorrect star allele assignments.

Examples of the problem are as follows:
(1) In the case of CYP2C9*6, the variant rs9332131 is a deletion of 'A'. However, ALDY fails to detect this deletion and wrongly assigns *6 as *1.
(rs9332131 recorded in cyp2c9.yml as [16126, delA, rs9332131, K273fs])

(2) For CYP3A5*7.001, one of its variants (rs41303343) contains an insertion 'T' that ALDY cannot detect, resulting in misidentification of *7 as 1.002.

(3) UGT1A1 *28 , UGT1A1 *36 , and UGT1A1 *37 all have rs3064744 with insertions 'TA' or deletions 'TA,' and ALDY is unable to detect these, failing to identify the correct alleles.

(4) Additionally, in the case of CYP2C19 *39, one of the ten variants is 4193delT, causing ALDY to produce a result of (CYP2C19 *39.001 - rs17880036).

Is there any specific configuration or setting that needs to be adjusted in ALDY to enable the correct detection of insertion and deletion variants? Your guidance and support would be highly appreciated.

`aldy genotype -p illumina --gene cyp2c9 --genome hg38 my.vcf -o my.cyp2c9.aldy`

Thank you for your attention and support.

**Comment by inumanag** [comment]
Hi @yscindyliu 

Aldy should be able to pick those up. As it seems that you are using VCF files, it might be the problem with our VCF parser.

Can you please show me the relevant VCF lines that have those variants so that I can see if it is a problem in our VCF parser?

**Comment by yscindyliu** [comment]
Thanks for getting back to me.

These are the positions in VCF:
(1) CYP2C9*6.001  
- [16126, delA, rs9332131, K273fs]
chr10   94949281    .   GA  G   4805.73 PASS    AC=1;AF=0.500;AN=2;BaseQRankSum=-4.790e-01;ClippingRankSum=0.      00;DP=311;ExcessHet=3.0103;FS=1.520;MLEAC=1;MLEAF=0.500;MQ=60.14;MQRankSum=1.92;QD=16.24;ReadPosRankSum=-4.53      0e-01;SOR=0.583   GT:AD:DP:GQ:PL  0/1:141,155:296:99:4843,0,4364

(2) CYP3A5*7.001  
- [32228, insT, rs41303343, T346fs]
chr7    99652770    .   T   TA

(3)UGT1A1 *28 , UGT1A1 *36 , and UGT1A1 *37 all have rs3064744 
- [175494, insTA, rs3064744, Promoter]
chr2    233760233   .   C   CAT

(4)CYP2C19 *39.001-rs17880036
- [4193, delT, rs17880036]
chr10   94761863    .   AT  A

(5)NUDT15*2.001  and   NUDT15*6.001:
- [5235, insGAGTCG, rs746071566, V18_V19insGV]   
chr13   48037782    .   A   AGGAGTC

**Comment by inumanag** [comment]
Hi @yscindyliu 

Those ambiguous tandem indels have many different interpretations (e.g., NUDT15 indel is at chr13:48037801 in our database). While Aldy accounts for these issues when using SAM/BAM files, we do not currently handle them with VCFs. 

Another thing that might help is to correct VCFs with IndelRealigner or similar tools that move all such indels to their "canonical" positions.

Also, make sure to set up genome (hg38) for VCFs manually via `--genome`.
