### ISSUE TITLE
Error: The average coverage of the sample is too low

### ISSUE THREAD

**Issue by rrdavis77** [0xTCG/aldy#66]
I have a set of 4 exomes and running aldy 4.4 on them as so:

aldy genotype -g cyp2e1 -p wxs  ${bam_location}/*/${sample_name}.bam -o ${output}/${sample_name}.cyp2d6.aldy -l ${output}/${sample_name}.cyp2e1.aldylog

for 3 out of the 4 exomes I am getting errors about the `The average coverage of the sample is too low`

`[main] arguments= subparser=genotype verbosity=INFO file=/home/ryan/NGS_Data/Exome_9-14-23/dragen_analysis/CYP-028/CYP-028.bam gene=cyp2e1 profile=wxs reference=None genome=None cn_neutral_region=None output=/home/ryan/NGS_Data/Exome_9-14-23/vcf/haplotype_aldy4_results_June_2023/CYP-028.CYP2E1.aldy solver=any debug=None cn=None log=/home/ryan/NGS_Data/Exome_9-14-23/vcf/haplotype_aldy4_results_June_2023/CYP-028.CYP2E1.aldylog multiple_warn_level=1 simple=False param=None
Genotyping sample CYP-028.bam...
WARNING: Copy-number calling is not available for exome data.
WARNING: Aldy will NOT be able to detect gene duplications, deletions and fusions.
WARNING: Calling of alleles that are defined by non-exonic mutations is not available.
         Results might not be biologically relevant!
[genotype] gene=cyp2e1; start=2023-09-27 18:52:17.572901
[lp] solver= cbc
[genotype] reference= hg19
[params] neutral_value=786.0; cn_parsimony=1.0; min_coverage=5.0
[sam] path= /home/ryan/NGS_Data/Exome_9-14-23/dragen_analysis/CYP-028/CYP-028.bam
[sam] Read SAM took 1.22s
[coverage] scale_ratio: 1.5
[sam] avg_coverage= 43.8x
ERROR: gene= cyp2e1, profile= wxs, file= /home/ryan/NGS_Data/Exome_9-14-23/dragen_analysis/CYP-028/CYP-028.bam
The average coverage of the sample is too low (1.9).`

I have looked at the metrics for coverage for this particular sample and dragen reports 113X coverage over the target bed for the IDT exome capture probes.  How should I resolve this?  Thanks!

Edit: adding the debug info for one of these samples: 
[debuginfo.tar.gz](https://github.com/0xTCG/aldy/files/12752638/debuginfo.tar.gz)

**Comment by inumanag** [comment]
Hi @rrdavis77 

I will soon release the version where you will be able to disable average coverage check (via `--param min_avg_coverage=0`).

(Duplicate: #49)
