### ISSUE TITLE
Aldy test error

### ISSUE THREAD

**Issue by TuBieJun** [0xTCG/aldy#69]
I run aldy test get the error result:

<img width="1154" alt="image" src="https://github.com/0xTCG/aldy/assets/15261087/8293e0a5-cdcd-4ef5-8586-6b82bf2d8918">
<img width="1901" alt="image" src="https://github.com/0xTCG/aldy/assets/15261087/56ebfcdd-6283-4909-8966-73bb12b959e8">

**Comment by husamia** [comment]
@TuBieJun I was getting this issue as well and I solved it by copying the contents of the folder pharmacoscan to the following location

`cp -r pharmacoscan/ /usr/local/lib/python3.11/site-packages/aldy/resources/genes`

**Comment by TuBieJun** [comment]
> @TuBieJun I was getting this issue as well and I solved it by copying the contents of the folder pharmacoscan to the following location
> 
> `cp -r pharmacoscan/ /usr/local/lib/python3.11/site-packages/aldy/resources/genes`
![image](https://github.com/0xTCG/aldy/assets/15261087/3c1bcfd8-5b1a-45a2-b729-6b971b0d52a0)


Yes, it looks like the pharmacoscan folder is not placed in the correct location.

**Comment by oiiio** [comment]
The pharmacoscan folder doesn't seem to install at all if you examine the result in site-packages/, just needs to fix that I think?

**Comment by mathob** [comment]
> The pharmacoscan folder doesn't seem to install at all if you examine the result in site-packages/, just needs to fix that I think?

I concur, after pip installation there is no pharmacoscan directory

**Comment by jonsonying** [comment]
> @TuBieJun I was getting this issue as well and I solved it by copying the contents of the folder pharmacoscan to the following location
> 
> `cp -r pharmacoscan/ /usr/local/lib/python3.11/site-packages/aldy/resources/genes`

It works for me. Remember to clone this repo to get the pharmacoscan folder first
