### ISSUE TITLE
Genotyping error using long read data

### ISSUE THREAD

**Issue by sumudu-rangika** [0xTCG/aldy#70]
Hi,

I am using Aldy v4.5 (Python 3.7.1 on Linux) to genotype Oxford Nanopore WGS data in phased BAM files. First I created a profile using one of my long read bam files without any CNVs or SVs in my interested regions. This ended without any errors. 

`aldy profile --cn-neutral-region chr12:47841536-47905031 --genome hg38 mybam.pass.phased.bam > m2.profile`

Line below was added to the beginning of the profile. 
options:
  sam_long_reads: true

This profile was used to call genotypes but this step ended with error. The command was run with the --debug and the folder is attached. 

`aldy genotype -g ${gene} -p m2.profile --cn-neutral-region chr12:47841536-47905031 --genome hg38 --debug DEBUG -o $outDir/HG04216 -l $outDir/HG04216.log /work/NagarajLab_BG/0_Scratch/NagarajLab_BG/Long_Read_Data_Dec2023/1000G_ONT/HG04216.LSK110.R9.guppy632.sup.with5mC.pass.phased.bam`

The error I got:
Aldy v4.5 (Python 3.7.1 on Linux 4.12.14-122.183-default-x86_64-with-SuSE-12-x86_64)
   (c) 2016-2024 Aldy Authors. All rights reserved.
   Free for non-commercial/academic use only.
Genotyping sample HG04216.LSK110.R9.guppy632.sup.with5mC.pass.phased.bam...
ERROR: gene= cyp2d6, profile= m2.profile, file= /work/NagarajLab_BG/0_Scratch/NagarajLab_BG/Long_Read_Data_Dec2023/1000G_ONT/HG04216.LSK110.R9.guppy632.sup.with5mC.pass.phased.bam
-n is only valid with illumina or BAM profile

When I run without -n option, I got the error: 
Genotyping sample HG04216.LSK110.R9.guppy632.sup.with5mC.pass.phased.bam...
ERROR: gene= cyp2c19, file= HG04216.LSK110.R9.guppy632.sup.with5mC.pass.phased.bam
TypeError("object of type 'NoneType' has no len()")
Traceback (most recent call last):
  File "/home/n11009985/.local/lib/python3.7/site-packages/aldy/__main__.py", line 122, in main
    _genotype(args.gene, output, args)
  File "/home/n11009985/.local/lib/python3.7/site-packages/aldy/__main__.py", line 443, in _genotype
    run(None)
  File "/home/n11009985/.local/lib/python3.7/site-packages/aldy/__main__.py", line 403, in run
    **{k: v for k, v in params.items() if v is not None},
  File "/home/n11009985/.local/lib/python3.7/site-packages/aldy/genotype.py", line 186, in genotype
    sample = sam.Sample(gene, profile, sam_path, reference, debug)
  File "/home/n11009985/.local/lib/python3.7/site-packages/aldy/sam.py", line 111, in __init__
    norm, muts = self._load_long_sam(path, reference, debug)
  File "/home/n11009985/.local/lib/python3.7/site-packages/aldy/sam.py", line 713, in _load_long_sam
    qual = read.query_qualities if read.query_qualities else [40] * len(seq)
TypeError: object of type 'NoneType' has no len()

Please also note that, when installing aldy4.5 I ended up getting the same 3 failures as mentioned here #55 , but assumed safe to ignore as you have mentioned. Hope this still holds. 

Greatly appreciate if you would help me to solve this error. 

Thank you
Best Regards
Sumudu

**Comment by sumudu-rangika** [comment]
Here is the debug file for the above issue. 
[DEBUG.tar.gz](https://github.com/0xTCG/aldy/files/13815768/DEBUG.tar.gz)

**Comment by inumanag** [comment]
Fixed in #70
