### ISSUE TITLE
Positions of variants are not identical between the *.vcf output and the standard *.aldy

### ISSUE THREAD

**Issue by Taalouane** [0xTCG/aldy#80]
Hello, 
The genomic positions of variants are not identical between the *.vcf output and the standard *.aldy output. The positions in the VCF file are correct, but the output in the *aldy file is always shifted by 1. I have tested several BAM files (as input) from gene panels, but I always get the same results

Here is the command used: 
`aldy genotype -p wxs --genome hg38 sample.bam -o sample.aldy
`
Has this problem been encountered before? Any ideas on how to solve it?"

Thanks

**Comment by aroon-color** [comment]
VCFs are defined as 1-indexed, e.g. the first base/position is 1, and BAMs (and Aldy as a result) are 0-indexed, e.g. the first base/position is 0. Aldy reports variants according to their position in the alignment

**Comment by inumanag** [comment]
Yes, Aldy uses 0-based indexing (as per BAM). I will add a clarification in the documentation :)
